/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookConsultationRouteImport } from './routes/book-consultation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as EligibilityIndexRouteImport } from './routes/eligibility.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as EligibilityUkSkilledWorkerVisaCalculatorRouteImport } from './routes/eligibility.uk.skilled-worker-visa-calculator'
import { Route as EligibilityUkSkilledWorkerCalculatorRouteImport } from './routes/eligibility.uk.skilled-worker-calculator'
import { Route as EligibilityGermanyOpportunityCardCalculatorRouteImport } from './routes/eligibility.germany.opportunity-card-calculator'
import { Route as EligibilityCanadaSaskatchewanSinpCalculatorRouteImport } from './routes/eligibility.canada.saskatchewan-sinp-calculator'
import { Route as EligibilityCanadaQuebecSkilledWorkerProgramRouteImport } from './routes/eligibility.canada.quebec-skilled-worker-program'
import { Route as EligibilityCanadaFederalSkilledWorkerProgramRouteImport } from './routes/eligibility.canada.federal-skilled-worker-program'
import { Route as EligibilityCanadaCrsCalculatorRouteImport } from './routes/eligibility.canada.crs-calculator'
import { Route as EligibilityAustralia491PointsCalculatorRouteImport } from './routes/eligibility.australia.491-points-calculator'
import { Route as EligibilityAustralia190PointsCalculatorRouteImport } from './routes/eligibility.australia.190-points-calculator'
import { Route as EligibilityAustralia189PointsCalculatorRouteImport } from './routes/eligibility.australia.189-points-calculator'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicGscSubmitSitemapRouteImport } from './routes/api/public/gsc/submit-sitemap'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConsultationRoute = BookConsultationRouteImport.update({
  id: '/book-consultation',
  path: '/book-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityIndexRoute = EligibilityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EligibilityRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityUkSkilledWorkerVisaCalculatorRoute =
  EligibilityUkSkilledWorkerVisaCalculatorRouteImport.update({
    id: '/uk/skilled-worker-visa-calculator',
    path: '/uk/skilled-worker-visa-calculator',
    getParentRoute: () => EligibilityRoute,
  } as any)
const EligibilityUkSkilledWorkerCalculatorRoute =
  EligibilityUkSkilledWorkerCalculatorRouteImport.update({
    id: '/uk/skilled-worker-calculator',
    path: '/uk/skilled-worker-calculator',
    getParentRoute: () => EligibilityRoute,
  } as any)
const EligibilityGermanyOpportunityCardCalculatorRoute =
  EligibilityGermanyOpportunityCardCalculatorRouteImport.update({
    id: '/germany/opportunity-card-calculator',
    path: '/germany/opportunity-card-calculator',
    getParentRoute: () => EligibilityRoute,
  } as any)
const EligibilityCanadaSaskatchewanSinpCalculatorRoute =
  EligibilityCanadaSaskatchewanSinpCalculatorRouteImport.update({
    id: '/canada/saskatchewan-sinp-calculator',
    path: '/canada/saskatchewan-sinp-calculator',
    getParentRoute: () => EligibilityRoute,
  } as any)
const EligibilityCanadaQuebecSkilledWorkerProgramRoute =
  EligibilityCanadaQuebecSkilledWorkerProgramRouteImport.update({
    id: '/canada/quebec-skilled-worker-program',
    path: '/canada/quebec-skilled-worker-program',
    getParentRoute: () => EligibilityRoute,
  } as any)
const EligibilityCanadaFederalSkilledWorkerProgramRoute =
  EligibilityCanadaFederalSkilledWorkerProgramRouteImport.update({
    id: '/canada/federal-skilled-worker-program',
    path: '/canada/federal-skilled-worker-program',
    getParentRoute: () => EligibilityRoute,
  } as any)
const EligibilityCanadaCrsCalculatorRoute =
  EligibilityCanadaCrsCalculatorRouteImport.update({
    id: '/canada/crs-calculator',
    path: '/canada/crs-calculator',
    getParentRoute: () => EligibilityRoute,
  } as any)
const EligibilityAustralia491PointsCalculatorRoute =
  EligibilityAustralia491PointsCalculatorRouteImport.update({
    id: '/australia/491-points-calculator',
    path: '/australia/491-points-calculator',
    getParentRoute: () => EligibilityRoute,
  } as any)
const EligibilityAustralia190PointsCalculatorRoute =
  EligibilityAustralia190PointsCalculatorRouteImport.update({
    id: '/australia/190-points-calculator',
    path: '/australia/190-points-calculator',
    getParentRoute: () => EligibilityRoute,
  } as any)
const EligibilityAustralia189PointsCalculatorRoute =
  EligibilityAustralia189PointsCalculatorRouteImport.update({
    id: '/australia/189-points-calculator',
    path: '/australia/189-points-calculator',
    getParentRoute: () => EligibilityRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGscSubmitSitemapRoute =
  ApiPublicGscSubmitSitemapRouteImport.update({
    id: '/api/public/gsc/submit-sitemap',
    path: '/api/public/gsc/submit-sitemap',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/eligibility': typeof EligibilityRouteWithChildren
  '/faq': typeof FaqRoute
  '/leads': typeof LeadsRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/eligibility/': typeof EligibilityIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/eligibility/australia/189-points-calculator': typeof EligibilityAustralia189PointsCalculatorRoute
  '/eligibility/australia/190-points-calculator': typeof EligibilityAustralia190PointsCalculatorRoute
  '/eligibility/australia/491-points-calculator': typeof EligibilityAustralia491PointsCalculatorRoute
  '/eligibility/canada/crs-calculator': typeof EligibilityCanadaCrsCalculatorRoute
  '/eligibility/canada/federal-skilled-worker-program': typeof EligibilityCanadaFederalSkilledWorkerProgramRoute
  '/eligibility/canada/quebec-skilled-worker-program': typeof EligibilityCanadaQuebecSkilledWorkerProgramRoute
  '/eligibility/canada/saskatchewan-sinp-calculator': typeof EligibilityCanadaSaskatchewanSinpCalculatorRoute
  '/eligibility/germany/opportunity-card-calculator': typeof EligibilityGermanyOpportunityCardCalculatorRoute
  '/eligibility/uk/skilled-worker-calculator': typeof EligibilityUkSkilledWorkerCalculatorRoute
  '/eligibility/uk/skilled-worker-visa-calculator': typeof EligibilityUkSkilledWorkerVisaCalculatorRoute
  '/api/public/gsc/submit-sitemap': typeof ApiPublicGscSubmitSitemapRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/leads': typeof LeadsRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/eligibility': typeof EligibilityIndexRoute
  '/services': typeof ServicesIndexRoute
  '/eligibility/australia/189-points-calculator': typeof EligibilityAustralia189PointsCalculatorRoute
  '/eligibility/australia/190-points-calculator': typeof EligibilityAustralia190PointsCalculatorRoute
  '/eligibility/australia/491-points-calculator': typeof EligibilityAustralia491PointsCalculatorRoute
  '/eligibility/canada/crs-calculator': typeof EligibilityCanadaCrsCalculatorRoute
  '/eligibility/canada/federal-skilled-worker-program': typeof EligibilityCanadaFederalSkilledWorkerProgramRoute
  '/eligibility/canada/quebec-skilled-worker-program': typeof EligibilityCanadaQuebecSkilledWorkerProgramRoute
  '/eligibility/canada/saskatchewan-sinp-calculator': typeof EligibilityCanadaSaskatchewanSinpCalculatorRoute
  '/eligibility/germany/opportunity-card-calculator': typeof EligibilityGermanyOpportunityCardCalculatorRoute
  '/eligibility/uk/skilled-worker-calculator': typeof EligibilityUkSkilledWorkerCalculatorRoute
  '/eligibility/uk/skilled-worker-visa-calculator': typeof EligibilityUkSkilledWorkerVisaCalculatorRoute
  '/api/public/gsc/submit-sitemap': typeof ApiPublicGscSubmitSitemapRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/eligibility': typeof EligibilityRouteWithChildren
  '/faq': typeof FaqRoute
  '/leads': typeof LeadsRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/eligibility/': typeof EligibilityIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/eligibility/australia/189-points-calculator': typeof EligibilityAustralia189PointsCalculatorRoute
  '/eligibility/australia/190-points-calculator': typeof EligibilityAustralia190PointsCalculatorRoute
  '/eligibility/australia/491-points-calculator': typeof EligibilityAustralia491PointsCalculatorRoute
  '/eligibility/canada/crs-calculator': typeof EligibilityCanadaCrsCalculatorRoute
  '/eligibility/canada/federal-skilled-worker-program': typeof EligibilityCanadaFederalSkilledWorkerProgramRoute
  '/eligibility/canada/quebec-skilled-worker-program': typeof EligibilityCanadaQuebecSkilledWorkerProgramRoute
  '/eligibility/canada/saskatchewan-sinp-calculator': typeof EligibilityCanadaSaskatchewanSinpCalculatorRoute
  '/eligibility/germany/opportunity-card-calculator': typeof EligibilityGermanyOpportunityCardCalculatorRoute
  '/eligibility/uk/skilled-worker-calculator': typeof EligibilityUkSkilledWorkerCalculatorRoute
  '/eligibility/uk/skilled-worker-visa-calculator': typeof EligibilityUkSkilledWorkerVisaCalculatorRoute
  '/api/public/gsc/submit-sitemap': typeof ApiPublicGscSubmitSitemapRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book-consultation'
    | '/contact'
    | '/eligibility'
    | '/faq'
    | '/leads'
    | '/privacy'
    | '/refund'
    | '/sitemap.xml'
    | '/success-stories'
    | '/terms'
    | '/admin/blog'
    | '/blog/$slug'
    | '/programs/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/eligibility/'
    | '/services/'
    | '/eligibility/australia/189-points-calculator'
    | '/eligibility/australia/190-points-calculator'
    | '/eligibility/australia/491-points-calculator'
    | '/eligibility/canada/crs-calculator'
    | '/eligibility/canada/federal-skilled-worker-program'
    | '/eligibility/canada/quebec-skilled-worker-program'
    | '/eligibility/canada/saskatchewan-sinp-calculator'
    | '/eligibility/germany/opportunity-card-calculator'
    | '/eligibility/uk/skilled-worker-calculator'
    | '/eligibility/uk/skilled-worker-visa-calculator'
    | '/api/public/gsc/submit-sitemap'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book-consultation'
    | '/contact'
    | '/faq'
    | '/leads'
    | '/privacy'
    | '/refund'
    | '/sitemap.xml'
    | '/success-stories'
    | '/terms'
    | '/admin/blog'
    | '/blog/$slug'
    | '/programs/$slug'
    | '/services/$slug'
    | '/blog'
    | '/eligibility'
    | '/services'
    | '/eligibility/australia/189-points-calculator'
    | '/eligibility/australia/190-points-calculator'
    | '/eligibility/australia/491-points-calculator'
    | '/eligibility/canada/crs-calculator'
    | '/eligibility/canada/federal-skilled-worker-program'
    | '/eligibility/canada/quebec-skilled-worker-program'
    | '/eligibility/canada/saskatchewan-sinp-calculator'
    | '/eligibility/germany/opportunity-card-calculator'
    | '/eligibility/uk/skilled-worker-calculator'
    | '/eligibility/uk/skilled-worker-visa-calculator'
    | '/api/public/gsc/submit-sitemap'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book-consultation'
    | '/contact'
    | '/eligibility'
    | '/faq'
    | '/leads'
    | '/privacy'
    | '/refund'
    | '/sitemap.xml'
    | '/success-stories'
    | '/terms'
    | '/admin/blog'
    | '/blog/$slug'
    | '/programs/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/eligibility/'
    | '/services/'
    | '/eligibility/australia/189-points-calculator'
    | '/eligibility/australia/190-points-calculator'
    | '/eligibility/australia/491-points-calculator'
    | '/eligibility/canada/crs-calculator'
    | '/eligibility/canada/federal-skilled-worker-program'
    | '/eligibility/canada/quebec-skilled-worker-program'
    | '/eligibility/canada/saskatchewan-sinp-calculator'
    | '/eligibility/germany/opportunity-card-calculator'
    | '/eligibility/uk/skilled-worker-calculator'
    | '/eligibility/uk/skilled-worker-visa-calculator'
    | '/api/public/gsc/submit-sitemap'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookConsultationRoute: typeof BookConsultationRoute
  ContactRoute: typeof ContactRoute
  EligibilityRoute: typeof EligibilityRouteWithChildren
  FaqRoute: typeof FaqRoute
  LeadsRoute: typeof LeadsRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TermsRoute: typeof TermsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiPublicGscSubmitSitemapRoute: typeof ApiPublicGscSubmitSitemapRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-consultation': {
      id: '/book-consultation'
      path: '/book-consultation'
      fullPath: '/book-consultation'
      preLoaderRoute: typeof BookConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility/': {
      id: '/eligibility/'
      path: '/'
      fullPath: '/eligibility/'
      preLoaderRoute: typeof EligibilityIndexRouteImport
      parentRoute: typeof EligibilityRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility/uk/skilled-worker-visa-calculator': {
      id: '/eligibility/uk/skilled-worker-visa-calculator'
      path: '/uk/skilled-worker-visa-calculator'
      fullPath: '/eligibility/uk/skilled-worker-visa-calculator'
      preLoaderRoute: typeof EligibilityUkSkilledWorkerVisaCalculatorRouteImport
      parentRoute: typeof EligibilityRoute
    }
    '/eligibility/uk/skilled-worker-calculator': {
      id: '/eligibility/uk/skilled-worker-calculator'
      path: '/uk/skilled-worker-calculator'
      fullPath: '/eligibility/uk/skilled-worker-calculator'
      preLoaderRoute: typeof EligibilityUkSkilledWorkerCalculatorRouteImport
      parentRoute: typeof EligibilityRoute
    }
    '/eligibility/germany/opportunity-card-calculator': {
      id: '/eligibility/germany/opportunity-card-calculator'
      path: '/germany/opportunity-card-calculator'
      fullPath: '/eligibility/germany/opportunity-card-calculator'
      preLoaderRoute: typeof EligibilityGermanyOpportunityCardCalculatorRouteImport
      parentRoute: typeof EligibilityRoute
    }
    '/eligibility/canada/saskatchewan-sinp-calculator': {
      id: '/eligibility/canada/saskatchewan-sinp-calculator'
      path: '/canada/saskatchewan-sinp-calculator'
      fullPath: '/eligibility/canada/saskatchewan-sinp-calculator'
      preLoaderRoute: typeof EligibilityCanadaSaskatchewanSinpCalculatorRouteImport
      parentRoute: typeof EligibilityRoute
    }
    '/eligibility/canada/quebec-skilled-worker-program': {
      id: '/eligibility/canada/quebec-skilled-worker-program'
      path: '/canada/quebec-skilled-worker-program'
      fullPath: '/eligibility/canada/quebec-skilled-worker-program'
      preLoaderRoute: typeof EligibilityCanadaQuebecSkilledWorkerProgramRouteImport
      parentRoute: typeof EligibilityRoute
    }
    '/eligibility/canada/federal-skilled-worker-program': {
      id: '/eligibility/canada/federal-skilled-worker-program'
      path: '/canada/federal-skilled-worker-program'
      fullPath: '/eligibility/canada/federal-skilled-worker-program'
      preLoaderRoute: typeof EligibilityCanadaFederalSkilledWorkerProgramRouteImport
      parentRoute: typeof EligibilityRoute
    }
    '/eligibility/canada/crs-calculator': {
      id: '/eligibility/canada/crs-calculator'
      path: '/canada/crs-calculator'
      fullPath: '/eligibility/canada/crs-calculator'
      preLoaderRoute: typeof EligibilityCanadaCrsCalculatorRouteImport
      parentRoute: typeof EligibilityRoute
    }
    '/eligibility/australia/491-points-calculator': {
      id: '/eligibility/australia/491-points-calculator'
      path: '/australia/491-points-calculator'
      fullPath: '/eligibility/australia/491-points-calculator'
      preLoaderRoute: typeof EligibilityAustralia491PointsCalculatorRouteImport
      parentRoute: typeof EligibilityRoute
    }
    '/eligibility/australia/190-points-calculator': {
      id: '/eligibility/australia/190-points-calculator'
      path: '/australia/190-points-calculator'
      fullPath: '/eligibility/australia/190-points-calculator'
      preLoaderRoute: typeof EligibilityAustralia190PointsCalculatorRouteImport
      parentRoute: typeof EligibilityRoute
    }
    '/eligibility/australia/189-points-calculator': {
      id: '/eligibility/australia/189-points-calculator'
      path: '/australia/189-points-calculator'
      fullPath: '/eligibility/australia/189-points-calculator'
      preLoaderRoute: typeof EligibilityAustralia189PointsCalculatorRouteImport
      parentRoute: typeof EligibilityRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gsc/submit-sitemap': {
      id: '/api/public/gsc/submit-sitemap'
      path: '/api/public/gsc/submit-sitemap'
      fullPath: '/api/public/gsc/submit-sitemap'
      preLoaderRoute: typeof ApiPublicGscSubmitSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EligibilityRouteChildren {
  EligibilityIndexRoute: typeof EligibilityIndexRoute
  EligibilityAustralia189PointsCalculatorRoute: typeof EligibilityAustralia189PointsCalculatorRoute
  EligibilityAustralia190PointsCalculatorRoute: typeof EligibilityAustralia190PointsCalculatorRoute
  EligibilityAustralia491PointsCalculatorRoute: typeof EligibilityAustralia491PointsCalculatorRoute
  EligibilityCanadaCrsCalculatorRoute: typeof EligibilityCanadaCrsCalculatorRoute
  EligibilityCanadaFederalSkilledWorkerProgramRoute: typeof EligibilityCanadaFederalSkilledWorkerProgramRoute
  EligibilityCanadaQuebecSkilledWorkerProgramRoute: typeof EligibilityCanadaQuebecSkilledWorkerProgramRoute
  EligibilityCanadaSaskatchewanSinpCalculatorRoute: typeof EligibilityCanadaSaskatchewanSinpCalculatorRoute
  EligibilityGermanyOpportunityCardCalculatorRoute: typeof EligibilityGermanyOpportunityCardCalculatorRoute
  EligibilityUkSkilledWorkerCalculatorRoute: typeof EligibilityUkSkilledWorkerCalculatorRoute
  EligibilityUkSkilledWorkerVisaCalculatorRoute: typeof EligibilityUkSkilledWorkerVisaCalculatorRoute
}

const EligibilityRouteChildren: EligibilityRouteChildren = {
  EligibilityIndexRoute: EligibilityIndexRoute,
  EligibilityAustralia189PointsCalculatorRoute:
    EligibilityAustralia189PointsCalculatorRoute,
  EligibilityAustralia190PointsCalculatorRoute:
    EligibilityAustralia190PointsCalculatorRoute,
  EligibilityAustralia491PointsCalculatorRoute:
    EligibilityAustralia491PointsCalculatorRoute,
  EligibilityCanadaCrsCalculatorRoute: EligibilityCanadaCrsCalculatorRoute,
  EligibilityCanadaFederalSkilledWorkerProgramRoute:
    EligibilityCanadaFederalSkilledWorkerProgramRoute,
  EligibilityCanadaQuebecSkilledWorkerProgramRoute:
    EligibilityCanadaQuebecSkilledWorkerProgramRoute,
  EligibilityCanadaSaskatchewanSinpCalculatorRoute:
    EligibilityCanadaSaskatchewanSinpCalculatorRoute,
  EligibilityGermanyOpportunityCardCalculatorRoute:
    EligibilityGermanyOpportunityCardCalculatorRoute,
  EligibilityUkSkilledWorkerCalculatorRoute:
    EligibilityUkSkilledWorkerCalculatorRoute,
  EligibilityUkSkilledWorkerVisaCalculatorRoute:
    EligibilityUkSkilledWorkerVisaCalculatorRoute,
}

const EligibilityRouteWithChildren = EligibilityRoute._addFileChildren(
  EligibilityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookConsultationRoute: BookConsultationRoute,
  ContactRoute: ContactRoute,
  EligibilityRoute: EligibilityRouteWithChildren,
  FaqRoute: FaqRoute,
  LeadsRoute: LeadsRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TermsRoute: TermsRoute,
  AdminBlogRoute: AdminBlogRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiPublicGscSubmitSitemapRoute: ApiPublicGscSubmitSitemapRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
